### ISSUE TITLE
Issue running learn

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/redux-dispatch-practice#3]
@Lukeghenco @aturkewi 
IMG of ISSUE when running `learn`

![screen shot 2017-02-13 at 3 08 24 pm](https://cloud.githubusercontent.com/assets/16408135/22903610/cec20df6-f1fe-11e6-9ead-488b5988a56d.png)

So the previous lesson `learn` worked. I've already updated my `learn-co gem` which didn't find any updates. Also i just `brew update && brew upgrade node && npm install -g npm`. So i have the latest version of node and npm. Also did `gem update --system` which updated my rubygems, but didn't fix the issue. Any other ideas why this doesn't work on my end?

OS: OSX el captain
node -v : 7.5.0
npm -v : 4.2.0
gem -v : 2.6.10

learn-co gems
learn-co : 3.7.0
learn-config: 1.0.77
learn-test: 2.4.0

Passed everything in the lesson: Browser didn't update. Will push my code to github and give link

github link: https://github.com/Enoch2k2/redux-dispatch-practice-learn-experts-testing-batch

**Comment by kwebster2** [comment]
@aturkewi  I also encountered this issue. It seems that the error is throwing because nothing is being output to the ".results.json" file when the tests run.

**Comment by aturkewi** [comment]
@Enoch2k2 are you still running into this?

Also, side note, it's much preferable to paste in code snippet rather than screen shot

**Comment by Enoch2k2** [comment]
I will keep that in mind @aturkewi ! Also i think the browser.js is also at fault here. I will test it after work tonight. If this is also the case, i will PR all the labs i had difficulties with :).

**Comment by achasveachas** [comment]
@aturkewi running into this issue as well. `npm test` has all the tests passing but running `learn` throws the same error that Enoch got.

**Comment by aturkewi** [comment]
@JeffKatzy

**Comment by kwebster2** [comment]
@aturkewi @Lukeghenco pull request #5 fixes this issue. The "mocha-nocache" dependency was interfering with the reporter output to the `.results.json` file, which caused the error when running `learn`.

**Comment by Lukeghenco** [comment]
Looks like this is closed up now @kwebster2 thanks
